### PR TITLE
TEST-1 - HTTP Authorization

### PR DESCRIPTION
**Pull request by cgamio**
Hey @macleanjr!! 

We've been getting email notifications that being able to auth GitHub requests by putting the token in the query string is being deprecated. I cooked this up to use the HTTP Authorization header for those requests instead, and it seems to be working. 

Let me know what you think :)

### CODE REVIEW

**Comment by macleanjr** [comment]
Thanks @cgamio -- will review this weekend and get a new version pushed out by Monday.

**Comment by jpolomcean1228** [comment]
@cgamio this looks like it can be used for CDS, Hearst, and Clear so long as the Github API key is set. Is that correct? BTW, HIII JASON! (that's me screaming)

**Comment by cgamio** [comment]
That functionality should be the same. My understanding is that as long as the repo is hosted by github and the token used has access to it, there shouldn’t be a problem

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by macleanjr** [comment]
@cgamio a new version has been submitted to the app store for review.  Once approved, it will auto update over the course of 24-72 hours.

Thanks again for making the updates!

**Pull request merged**
